[package]
name = "anchor-idl"
version = "0.1.2"
edition = "2021"
description = "Anchor IDL helpers."
authors = ["Ian Macalinao <ian@saber.so>"]
repository = "https://github.com/saber-hq/anchor-gen"
license = "Apache-2.0"
keywords = ["solana", "anchor"]

[dependencies]
heck = "0.4.0"
anchor-syn = { version = "0.24.2", features = ["idl"] }
proc-macro2 = "1"
quote = "1"
syn = { version = "1", features = ["full"] }

[dev-dependencies]
anchor-lang = "0.24.2"
